version: '2'
services:
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: dev-tool-db
    image: dev-tool-db:latest
    volumes:
      - /srv/mysql/db:/var/lib/mysql
    ports:
      - "3306:3306"
  php:
    container_name: dev-tool-php
    image: dev-tool-php:latest
    ports:
      - "9000:9000"

  memcached:
    container_name: dev-tool-memcached
    image: dev-tool-memcached:latest
    ports:
      - "11211:11211"

# networks:
#   default:
#     external:
#       name: dev-net
