version: '2'
services:

  db:
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: dev-tool-db
    image: dev-tool-db:latest
    volumes:
      - /srv/mysql/db:/var/lib/mysql
    ports:
      - "3306:3306"

  php:
    container_name: dev-tool-php
    image: dev-tool-php:latest
    volumes:
      - /srv/www:/www
    ports:
      - "9000:9000"

  memcached:
    container_name: dev-tool-memcached
    image: dev-tool-memcached:latest
    ports:
      - "11211:11211"

  redis:
    container_name: dev-tool-redis
    image: dev-tool-redis:latest
    ports:
      - "6379:6379"

  sphinx:
    container_name: dev-tool-sphinx
    image: dev-tool-sphinx:latest
    ports:
      - "9312:9312"
      - "9306:9306"

  nginx:
    container_name: dev-tool-nginx
    image: dev-tool-nginx:latest
    depends_on:
      - php
    volumes:
      - /srv/www:/www
      - /srv/logs/nginx:/var/log/nginx
    ports:
      - "80:80"

# networks:
#   default:
#     external:
#       name: dev-net
