---
php5_packages:
  - php-pear
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-fpm
  - php5-gd
  - php5-imagick
  - php5-intl
  - php5-json
  - php5-mcrypt
  - php5-memcached
  - php5-mysql
  - php5-pspell
  - php5-readline
  - php5-redis

# Default values for several global PHP5 options
php5_post_max_size: '8M'
php5_default_charset: 'UTF-8'
php5_file_uploads: 'On'
php5_upload_max_filesize: '{{ php5_post_max_size }}'
php5_max_file_uploads: 20
php5_allow_url_fopen: 'On'

php5_pools: [ '{{ php5_pool_default }}' ]
php5_pool_default:
  enabled: True
  name: 'www-data'
  listen: '0.0.0.0:9000'
  pm: 'dynamic'
  pm_status: False
