ansible_os_family: Debian
ansible_distribution:

nginx_remove_default_vhost: true

nginx_vhosts:
  - listen: "80 default_server"
    server_name: "example.com"
    root: "/www/example.com"
    index: "index.php"
    access_log: "/var/log/nginx/example.com_access.log"
    error_log: "/var/log/nginx/example.com_error.log"
    extra_parameters: |

        location = /favicon.ico {
                log_not_found off;
                access_log off;
        }

        location = /robots.txt {
                allow all;
                log_not_found off;
                access_log off;
        }

        location / {
                # This is cool because no php is touched for static content.
                # include the "?$args" part so non-default permalinks doesn't break when using query string
                try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass php:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
                expires max;
                log_not_found off;
        }
