---
- name: Install base packages
  apt:
    name={{ item }}
    state=latest
    install_recommends=no
  with_items:
    - ca-certificates
    - curl
    - file
    - git-core
    - iproute2
    - net-tools
    - netcat-openbsd
    - python-pip
    - strace
    - vim
    - wget
