---
- hosts: dev-tool-nginx
  gather_facts: no
  connection: docker

  vars_files:
    - vars/dev-tool-nginx.yml

  pre_tasks:
    - include: tasks/container-create.yml ansible_connection=local
    - include: tasks/apt-update.yml

  roles:
    - dev-tool-nginx

  post_tasks:
    - include: tasks/system-cleanup.yml
    - include: tasks/create-www-root.yml
    - include: tasks/container-commit.yml ansible_connection=local
