---
- hosts: dev-tool-db
  gather_facts: no
  connection: docker

  vars_files:
    - vars/dev-tool-db.yml

  pre_tasks:
    - include: tasks/container-create.yml ansible_connection=local
    - include: tasks/apt-update.yml

  roles:
    - dev-tool-db

  post_tasks:
    - include: tasks/system-cleanup.yml
    - include: tasks/container-commit.yml ansible_connection=local
